baseURL = 'https://Relish1one.github.io/'
languageCode = 'en'
# languageCode = 'zh-CN'
theme = "JuiceBar"
title = "R1one's Blog"

[params]
author = "R1one"
description = "My site description"
authorImage = "/images/profile.jpg"
paginate = 15

Title = "R1one"
content = "I'm R1one, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.jpg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/Relish1one"
[[params.social]]
name = "telegram"
url = " "
[[params.social]]
name = "twitter"
url = " "
[[params.social]]
name = "email"
url = "mailto:relish1one@163.com"

[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

[params.giscus]
repo = "hotjuicew/blog"
repoID = "R_kgDOHHQOuw"
category = "Announcements"
categoryID = "DIC_kwDOHHQOu84CWCQ3"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



